title: Timothy's Website
description: Academic Portfolio and Analytics Repository
theme: minima

# Prevents default theme links from clashing with our custom Bootstrap navbar
header_pages: []

baseurl: "/personal-website-1/" # exact GitHub repository name
url: "https://tninanofchirawa.github.io/personal-website-1/" # GitHub Pages URL

# _config.yml
google_analytics: G-LN7Y2T4WQV

